import type { Metadata } from 'next'
import { Providers } from './providers'
import { Navbar } from '@/components/Navbar'
import { Container } from '@chakra-ui/react'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>
        <Navbar />
        <Container maxW="container.lg">{children}</Container>
          </Providers>
      </body>
    </html>
  )
}